name : cluster-group-demo2
tags : ["owner:siva"]
clusters:
  - cluster_name: shruthi-dec21-stage
    host_dns: "*.spectrotest.com"
  - cluster_name: shruthi-eks-dec21-stage
    host_dns: "*.test.spsctrotext.com"
config:
  host_endpoint_type: Ingress
  cpu_millicore: 6000
  memory_in_mb: 8192
  storage_in_gb: 10
  oversubscription_percent: 120

