virtual_clusters:
  - name: virtual-cluster-module-demo1
    host_cluster_name: gcpimport
    resources:
      max_cpu: 6
      max_mem_in_mb: 6000
      min_cpu: 0
      min_mem_in_mb: 0
      max_storage_in_gb: 10
