virtual_clusters:
  - name: virtual-cluster-module-demo2
    host_cluster_name: a6-oprke2
    resources:
      max_cpu: 6
      max_mem_in_mb: 6000
      min_cpu: 1
      min_mem_in_mb: 1000
  - name: virtual-cluster-module-demo3
    cluster_group_name: vanilla-ingress
    resources:
      max_cpu: 3
      max_mem_in_mb: 3000
      min_cpu: 1
      min_mem_in_mb: 1000
