name: hospital-201
cloudType: edge-vsphere
edge_host_uid: hospital-201
tags:
- "skip_completion"
profiles:
  infra:
    name: vsphere-with-creds-infra
  system:
    name: hospital-201-system-profile
  addons:
   - name: spectro-core
cloud_config:
  ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCr3hE9IS5UUDPqNOiEWVJvVDS0v57QKjb1o9ubvvATQNg2T3x+inckfzfgX3et1H9X1oSp0FqY1+Mmy5nfTtTyIj5Get1cntcC4QqdZV8Op1tmpI01hYMj4lLn55WNaXgDt+35tJ47kWRr5RqTGV05MPNWN3klaVsePsqa+MgCjnLfCBiOz1tpBOgxqPNqtQPXh+/T/Ul6ZDUW/rySr9iNR9uGd04tYzD7wdTdvmZSRgWEre//IipNzMnnZC7El5KJCQn8ksF+DYY9eT9NtNFEMALTZC6hn8BnMc14zqxoJP/GNHftmig8TJC500Uofdr4OKTCRr1JwHS79Cx9LyZdAp/1D8mL6bIMyGOTPVQ8xUpmEYj77m1kdiCHCk22YtLyfUWuQ0SC+2p1soDoNfJUpmxcKboOTZsLq1HDCFrqSyLUWS1PrYZ/MzhsPrsDewB1iHLbYDt87r2odJOpxMO1vNWMOYontODdr5JPKBpCcd/noNyOy/m4Spntytfb/J3kM1oz3dpPfN0xXmC19uR1xHklmbtg1j784IMu7umI2ZCpUwLADAodkbxmbacdkp5I+1NFgrFamvnTjjQAvRexV31m4m9GielKFQ4tCCId2yagMBWRFn5taEhb3SKnRxBcAzaJLopUyErOtqxvSywGvb53v4MEShqBaQSUv4gHfw== spectro2022"
  vip: 192.168.100.15
  static_ip: false
  network_type: VIP
  datacenter: "Spectrocloud"
  folder: "demo-creds-1"
node_groups:
  - name: master-pool
    control_plane: true
    control_plane_as_worker: true
    count: 1
    disk_size_gb: 60
    memory_mb: 8192
    cpu: 2
    placement:
      cluster: "Spectrocloud"
      resource_pool: "Resources"
      datastore: "VOL_SC_CMP1_02"
      network: "Spectro-Pvt-Net05"

  - name: worker-pool
    count: 3
    disk_size_gb: 60
    memory_mb: 8192
    cpu: 4
    placement:
      cluster: "Spectrocloud"
      resource_pool: "Resources"
      datastore: "VOL_SC_CMP1_02"
      network: "Spectro-Pvt-Net05"

