name: app-tf-mysql
version: 2.0.0
context: project
description: created from tf-modules
cloud: all
pack:
  - name: mysql-3-prod
    type: operator-instance
    source_app_tier:
      name: mysql-operator
      version: 0.6.2
      registry_name: svtest
    properties:
      dbRootPassword: ${base64_encode_password}
      dbVolumeSize: 20
      version: 5.7
