name: libvirt-dev
cloudType: libvirt
profiles:
  infra:
    name: libvirt-gpu-full
cloud_config:
  ssh_key: spectro2022
  vip: 192.168.100.15
node_groups:
  - name: cp-pool
    control_plane: true
    control_plane_as_worker: true
    count: 1
    disk_size_gb: 60
    memory_mb: 8192
    cpu: 2
    cpus_sets: 1
    attached_disks_size_gb: "10"
    placements:
      - appliance: "libvirt-nik15-mar-21"
        network_type: "bridge"
        network_names: "br0"
        network: "br"
        image_storage_pool: "ehl_images"
        target_storage_pool: "ehl_images"
        data_storage_pool: "ehl_data"

  - name: worker-pool
    count: 3
    disk_size_gb: 60
    memory_mb: 8192
    cpu: 4
    cpus_sets: 1
    attached_disks_size_gb: "10"
    placements:
      - appliance: "libvirt-nik15-mar-21"
        network_type: "bridge"
        network_names: "br0"
        network: "br"
        image_storage_pool: "ehl_images"
        target_storage_pool: "ehl_images"
        data_storage_pool: "ehl_data"

scan_policy:
  configuration_scan_schedule: "0 0 * * SUN"
  penetration_scan_schedule: "0 0 * * SUN"
  conformance_scan_schedule: "0 0 1 * *"
