name: edge-tf
cloudType: edge-native
skip_completion: true
profiles:
  infra:
    name: byos-os-pxke-simple-tf-test
cloud_config:
  ssh_key: spectro2022
  vip: 1.1.1.1

node_groups:
  - name: master-pool
    control_plane: true
    control_plane_as_worker: true
    count: 1
#    placements:
#      - appliance: "edge-apr-5"
    host_uids: ["edge-apr-5"]

  - name: worker-pool
    count: 1
    placements:
      - appliance: "edge-apr-6"

    additional_labels:
      #name: "worker"
      addlabel: "addlabelval1"
    host_uids: ["edge-apr-6"]


#    taints:
#      - key: "taintkey1"
#        value: "taintvalue1"
#        effect: "PreferNoSchedule"
#      - key: "taintkey2"
#        value: "taintvalue2"
#        effect: "NoSchedule"
#
#scan_policy:
#  configuration_scan_schedule: "0 0 * * SUN"
#  penetration_scan_schedule: "0 0 * * SUN"
#  conformance_scan_schedule: "0 0 1 * *"
