name: hospital-200
cloudType: libvirt
tags:
- "skip_completion"
profiles:
  infra:
    name: bm-infra
  system:
    name: hospital-200-system-profile
  addons:
    - name: spectro-core
cloud_config:
  ssh_key: "ssh-rsa AADS0v57QKjb1o9ubvvATQNg2T3x+inckfzfgX3et1H9X1oSp0FqY1+Mmy5nfTtTyIj5GetePsqa+MgCjnLfCBiOzmZSRgWEre//IipNzMnnZC7El5KJCQn8ksF+DYY9eT9NtNFEMALTZC6hn8BnMc14zqxoJP/GNHftmig8TJC500Uofdr4OKTCRr1JwHS79Cx9LyZdAp/1D8mL6bIMyGOTPVQ8xUpmEYj77m1kdiCHCk22YtLyfUWuQ0SC+2p1soDoNfJUpmxcKboOTZsLq1HDCFrqSyLUWS1PrYZ/MzhsPrsDewB1iHLbYDt87r2odJOpxMO1vNWMOYontODdr5JPKBpCcd/noNyOy/m4Spntytfb/J3kM1oz3dpPfN0xXmC19uR1xHklmbtg1j784IMu7umI2ZCpUwLADAodkbxmbacdkp5I+1NFgrFamvnTjjQAvRexV31m4m9GielKFQ4tCCId2yagMBWRFn5taEhb3SKnRxBcAzaJLopUyErOtqxvSywGvb53v4MEShqBaQSUv4gHfw== spectro2022"
  vip: 192.168.100.15
  ntp_servers: ["ntp.ge.com"]
node_groups:
  - name: master-pool
    control_plane: true
    control_plane_as_worker: true
    count: 1
    disk_size_gb: 60
    memory_mb: 8192
    cpu: 2
    placements:
      - appliance: "hospital-200"
        network_type: "bridge"
        network_names: "br0"
        network: "br"
        image_storage_pool: "ehl_images"
        target_storage_pool: "ehl_images"
        data_storage_pool: "ehl_data"

  - name: worker-pool
    count: 3
    disk_size_gb: 60
    memory_mb: 8192
    cpu: 4
    attached_disks:
      - size_in_gb: 30
        managed: true
      - size_in_gb: 10
        managed: true
    placements:
      - appliance: "hospital-200"
        network_type: "bridge"
        network_names: "br0"
        network: "br"
        image_storage_pool: "ehl_images"
        target_storage_pool: "ehl_images"
        data_storage_pool: "ehl_data"
