project: Local-minikube
is_active: true
component: ClusterHealth
alert_all_users : false
type: http
identifiers:
  - sivaa@spectro.com
http:
  - method: POST
    url: 'https://openhook.com/put/dev0'
    body: '{ "text": "{{message}}" }'
    headers:
      src: spectro